Algoritmo "semnome"
// Disciplina  : Programação e algoritmos
// Professor   : Cintia Pinho
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Pedro Machado
// Data atual  : 31/08/2020
Var
// Seção de Declarações das variáveis 
x,n,soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Entre com o valor")
 leia(x)
 soma<-soma+x
 escreval("Resultado", soma)
 para n<- ate 10 faca
 fimpara
Fimalgoritmo
