Algoritmo "laço para"
// aula        : PA
// Professor   : Arnobio
// Descrição   : Realiza contagem de 0 até 9
// Autor(a)    : Pedro Machado
// Data atual  : 09/06/2020
Var
// Seção de Declarações das variáveis 
 conta: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa escreve os numeros de 0 até 9")
conta<-0
para conta de 0 ate 9 faca
escreval("conta=",conta)
fimpara

Fimalgoritmo