Algoritmo "laço para"
// aula        : PA
// Professor   : Arnobio
// Descrição   : Realiza contagem de 9 até 1
// Autor(a)    : Pedro Machado
// Data atual  : 09/06/2020
Var
// Seção de Declarações das variáveis 
conta:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval   ("Programa escreve numeros de 9 a 1")
conta<-9
para conta de 9 ate 1 passo -1 faca
escreval("conta=",conta)
fimpara

Fimalgoritmo