algoritmo "Multiplicação"
// Disciplina :  (Linguagem e Lógica de Programação)
// Professor :  Arnóbio
// Descrição: Executa Multiplicação
// Autor : Pedro Machado
// Data : 05/05/2020
var
// Seção de Declarações das variáveis
a,b,r:inteiro

inicio
a<-10
b<-5
escreval("Programa da Multiplicação")
escreval("O Valor de A é:",a)
escreval("O Valor de B é:",b)
 r<-a*b
 escreva("A Multiplicação de A e B é:",r)
 
fimalgoritmo
