algoritmo "Programa Soma"
//Disciplina : (Linguagem e Lógica de Programação)
//Professor : Arnóbio
//Descrição : Aqui você descreve o que o programa faz! (função)
// Autor :  Nicoly Holanda
// Data Atual : 05/05/2020
var
// Seção de Declarações das variáveis
a,b,r:inteiro

inicio
escreval ("Programa da Soma")
escreva ("Digite o valor de A: ")
leia(a)
escreva ("Digite o valor de B: ")
leia(b)
r<-(a+b)
escreva ("A Soma de A e B é: ", r)

fimalgoritmo
