algoritmo "Programa Soma"
//Disciplina : (Linguagem e Lógica de Programação)
//Professor : Arnóbio
//Descrição : Realiza soma
// Autor :  Pedro
// Data Atual : 05/05/2020
var
// Seção de Declarações das variáveis
a,b,r:inteiro

inicio
a<-10
b<-5
escreval ("Programa da Soma")
escreval ("O Valor de A é:", a)
escreval ("O Valor de B é:", b)
 r<-a+b
 escreva ("A Soma de A e B é:", r)

fimalgoritmo
